### ISSUE TITLE
can you share data for opn-rd2-acv

### ISSUE THREAD

**Issue by Sandy4321** [dwiuzila/data-science-competitions#1]
great code thanks

only 
can you share data for 
https://www.kaggle.com/c/opn-rd2-acv/data
they close data sharing 

also 
really great blog
https://towardsdatascience.com/complete-step-by-step-conjugate-gradient-algorithm-from-scratch-202c07fb52a8

do you have all code to downloads in one place ?

**Comment by dwiuzila** [comment]
Oh yes, they did. Do you have an email I can share the data with? I don't think sharing it publicly is allowed.

And thanks for stopping by to the blog. It's one among many: [Optimization Methods from Scratch](https://medium.com/@dwiuzila/list/b35db8650093). However, I'm sorry to say that the complete codes are only available for my [referred Medium member](https://dwiuzila.medium.com/membership). You can copy the code manually from the blog tho.

**Comment by Sandy4321** [comment]
yes pls send data to 
sndrstpnv@gmail.com
thanks

**Comment by dwiuzila** [comment]
Sent 👌
